version: '3.8'
services:
  web:
    build:  .
    command: uvicorn blog.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8080:8000
  db:
    container_name: mysqlDB
    hostname: mysqlDB
    image: mysql
    restart: always
    env_file:
      - .db.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: